### ISSUE TITLE
Where is the template?

### ISSUE THREAD

**Issue by dimagsweb** [SecTheater/marketplace#4]
Hello, where is the template for this marketplace? I have created a product but how can I show them in my template view

**Comment by SecTheater** [comment]
There is no template yet as this is a primary version, This version takes care of back-end, I will consider having a template in the coming versions, but at the moment you have to create your own  view and pass the data to it.

**Comment by SecTheater** [comment]
There is no template yet as this is a primary version, This version takes care of back-end, I will consider having a template in the coming versions, but at the moment you have to create your own  view and pass the data to it.

**Comment by SecTheater** [comment]
There is no template yet as this is a primary version, This version takes care of back-end, I will consider having a template in the coming versions, but at the moment you have to create your own  view and pass the data to it.
